AppBundle\Entity\InventorySlot:
    type: entity
    table: inventoryslot
    repositoryClass: AppBundle\Repository\InventorySlotRepository
    manyToOne:
        inventory:
            targetEntity: Inventory
            nullable: false
            inversedBy: slots
            joinColumn:
                name: inventory_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
            default: 0
            nullable: false
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
